### ISSUE TITLE
Auto-change theme depending on the theme of the system (browser)

### ISSUE THREAD

**Issue by rakleed** [rossmoody/svg-gobbler#137]
Could you add an auto change theme for the extension depending on the theme of the system (browser) and make this option the default?

Useful link: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by rossmoody** [comment]
Great suggestion. Going out in next release

**Comment by rakleed** [comment]
@rossmoody a light background appears on page reload.

https://user-images.githubusercontent.com/19418601/222748977-0b88a817-5cc5-41e2-a162-ab1b3f4d9836.mp4
