### ISSUE TITLE
Extracted SVG doesn't seem to propagate some styles

### ISSUE THREAD

**Issue by jonathan-neufeld-asurion** [rossmoody/svg-gobbler#151]
A dynamically generated SVG does not extract some styles probably because they are external dependencies.  I also took the script-generated `<svg></svg>` contents (using the browser developer tools) and placed it into an SVG file and reproduced the same result.

How the SVG appears inside the web browser:
![image](https://github.com/rossmoody/svg-gobbler/assets/73544551/9d847b0d-df59-4406-82fd-6336f74ec7e6)

How it appears after extraction and loading into _Inkscape_:
![image](https://github.com/rossmoody/svg-gobbler/assets/73544551/66e218a7-2322-43ef-8760-9b6323837a26)

I was also able to reproduce the same outcome visually by disabling a `fill` style via the developer tools:
![image](https://github.com/rossmoody/svg-gobbler/assets/73544551/dbdb06ef-6e12-4058-9a26-9f79697de015)

Please see attached files used to generate the SVG:
[dependency-graph.zip](https://github.com/rossmoody/svg-gobbler/files/12859845/dependency-graph.zip)

**Comment by rossmoody** [comment]
I'm not sure if this issue was for `svg-gobbler`. Closing for now but feel free to submit another if I am wrong.
