### ISSUE TITLE
Why do you force it to rename files?

### ISSUE THREAD

**Issue by jkinley** [rossmoody/svg-gobbler#171]
Great app, but this is a deal-breaker.

**Comment by rossmoody** [comment]
What is your preferred default behavior? There isn't really a filename associated with an svg to start.

**Comment by rossmoody** [comment]
@jkinley I want to address this but I'm unsure of how to go about it. Can you say a little more about what your desired functionality is?

**Comment by rossmoody** [comment]
@jkinley I'm going to close this without further info but I'm very curious for your take. I thought about this a bit more and one thing I think I can do to be more intuitive is pre-fill the filename with the domain instead of always defaulting to `svg-gobbler.svg`.
