### ISSUE TITLE
Please add more language switches.

### ISSUE THREAD

**Issue by GrainStar** [rossmoody/svg-gobbler#175]
Due to Google security restrictions, the translation plugin is unable to call this page. However, this plugin is extremely useful for designers and I believe it will be used by more people in the future. I can provide Chinese translation support.

**Comment by rossmoody** [comment]
This is exciting! Thanks for suggesting this and offering help. I'll get started on it this week. @GrainStar

**Comment by GrainStar** [comment]
> This is exciting! Thanks for suggesting this and offering help. I'll get started on it this week. @GrainStar

Thank you for adopting my suggestions on the requirements. Please reply to this message when everything is ready

**Comment by rossmoody** [comment]
Ok, @GrainStar, I used ChatGPT to generate some initial localizations for various languages, but I have no idea how effective it was. I can barely speak English.

**Comment by GrainStar** [comment]
> Ok, @GrainStar, I used ChatGPT to generate some initial localizations for various languages, but I have no idea how effective it was. I can barely speak English.

Hhhhh, Me too. My English is terrible too.
