### ISSUE TITLE
Gobbler doesn't appear to work on firefox 115.14.0esr 

### ISSUE THREAD

**Issue by p-sims** [rossmoody/svg-gobbler#201]
Just tried installing SVG Gobbler (v3.17.0) to try and export d3 Sankey from webpage to svg file....

I wasn't using a private tab, but regardless of whether that setting was allowed or not it still showed:
![Screenshot 2024-08-20 at 22 10 11](https://github.com/user-attachments/assets/83cb156c-13b1-4292-9a6d-d2c033bc41f8)

Hopefully useful feedback....

**Comment by rossmoody** [comment]
Sadly, with the introduction of manifest v3, I don't update the Firefox version of this extension anymore. I hope eventually the browser manifest can sync back up. Appreciate the issue all the same.
