### ISSUE TITLE
Visualisation issue after dowloading a SVG.

### ISSUE THREAD

**Issue by BaptisteB92** [rossmoody/svg-gobbler#210]
My browser shows me this page when i try to see the dowloaded PNG.
![Capture d’écran 2024-12-26 005551](https://github.com/user-attachments/assets/830f2b3c-0c24-498f-834f-d2ff31011ddd)

**Comment by rossmoody** [comment]
I believe the issue here is the sourced SVG is missing the valid XML namespace, like `xmlns="http://www.w3.org/2000/svg"` in order to render. The PNG won't render the SVG unless it has that.
