### ISSUE TITLE
White SVGs aren't visible on card

### ISSUE THREAD

**Issue by Tressley** [rossmoody/svg-gobbler#23]
If an SVG is white, it isn't visible on `.gob__card`

![image](https://user-images.githubusercontent.com/2686586/58648152-109fd300-82d7-11e9-8150-58abcae772dc.png)

For reference, this is the SVG that should be shown above:
![image](https://user-images.githubusercontent.com/2686586/58648267-58265f00-82d7-11e9-9ce0-6efd3b0e4fe0.png)

**Comment by rossmoody** [comment]
Good troubleshooting site for this: 
![image](https://user-images.githubusercontent.com/29072694/61233193-d81c5300-a6e4-11e9-9b47-6a97c2dd8af6.png)
https://sso.parler.com/login
