### ISSUE TITLE
Improve error handling 

### ISSUE THREAD

**Issue by rossmoody** [rossmoody/svg-gobbler#26]
There is a generic try catch but it would be a lot more helpful to provide accessible reasons for why the extension isn't working.

**Comment by NAjustin** [comment]
Running into this currently. Our team has many Google Data Studio reports that we're using this tool on, but on some the plugin fails to open and shows a generic error along these lines:
```
😢 There's an error: "TypeError: Cannot read property 'tagName' of null"
```

Unfortunately this makes it quite difficult to know what element it had an issue with. I'm thinking a short-term solution would be to output additional details to the console, such as the element that caused the error, any details from the SVG parsing, etc.

In some cases, file-level errors may be able to be gracefully handled and show an error card (so the user is aware that there was a problem), while still allowing other SVGs to be downloaded.

I'll try to make a reproducible case and see where I can take this from there.
