### ISSUE TITLE
Make extension for firefox

### ISSUE THREAD

**Issue by rossmoody** [rossmoody/svg-gobbler#42]
no idea how to do this

**Comment by voxpelli** [comment]
Here's an official how to: https://extensionworkshop.com/documentation/develop/porting-a-google-chrome-extension/

**Comment by rossmoody** [comment]
I actually ended up carrying this out successfully but I'm doing a really poor job communicating, updating and QCing it. Thanks for the ping on this and the literature. Gonna make sure I have all the boxes checked.

**Comment by rossmoody** [comment]
https://addons.mozilla.org/en-US/firefox/addon/svg-gobbler/
