### ISSUE TITLE
Preview sizes are missing for some SVGs since last update (breaking previews)

### ISSUE THREAD

**Issue by NAjustin** [rossmoody/svg-gobbler#48]
Since the last update, many SVGs are listed as 0x0 and don't generate correct previews in the interface despite working correctly previously.

An easy example of this is the charts generated by Google Data Studio, which can be tested against a public dashboard like this:
[https://datastudio.google.com/u/0/reporting/1vqvDNQ1bqXhY5awvsW1OOQbjYpTliKAg/page/bnFIB?s=oh1ENMEdT04](https://datastudio.google.com/u/0/reporting/1vqvDNQ1bqXhY5awvsW1OOQbjYpTliKAg/page/bnFIB?s=oh1ENMEdT04)

In the previous version, output for the main line chart looked like this:
![Google Data Studio example, showing working line chart preview](https://user-images.githubusercontent.com/51453105/76988062-2c31a400-6912-11ea-9942-5e40ee77d8f1.png)

In the current version, it looks like this:
![Google Data Studio example, showing blank chart and 0x0 size](https://user-images.githubusercontent.com/51453105/76988208-5c794280-6912-11ea-8250-203812c2fe8b.png)

The preview isn't actually blank, but rather just getting the top-left of the chart which happens to be all transparent. This makes it impossible to know which chart you're downloading.

I'm guessing this is probably all related to invalid detection of the size, but definitely a regression from the previous behavior. I've seen this on other sites too, but I'm not sure what the commonality is related to sizing. As you test, you'll see that number of the other elements on the page preview and calculate sizes just fine.

(I was originally hoping to get the time to fix this myself, but it's been seeming like that isn't very realistic with my current work schedule—so here's hoping someone else has the time!)

**Comment by rossmoody** [comment]
Thank you so much for spotting this and pointing this out. You're right, big regression. I went back and found where it veered. Will upload fix to Chrome store.

**Comment by NAjustin** [comment]
@rossmoody Ironically I started working on this fix on Friday too 😂

Thanks for all the time you've put in on this! I'm going to pull this round of updates and work on some feature additions (like adding an options page and a way to scale output SVGs by a multiplier so that they can right-fit when pasted in drop targets in various other products—something I thought only our team needed but has come up with a few other folks I told about the tool).
