### ISSUE TITLE
Feature Request: toggle light/dark background

### ISSUE THREAD

**Issue by chrismessina** [rossmoody/svg-gobbler#68]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/22610/103141127-9dbe3000-46a4-11eb-9997-c21b1942684a.png)

There are many occasions where it's not possible to see what a glyph/SVG asset actually looks like because its contents are the same color as the background color (as seen above).

**Describe the solution you'd like**
It would be useful to be able to toggle light/dark background modes.

**Describe alternatives you've considered**
I've tried to change the background-color style of the boxes using Inspect Element, but that's pretty inefficient.

**Additional context**
Here's the source of the page where I used the SVG Grabber: https://www.diffordsguide.com/

**Comment by rossmoody** [comment]
Really great suggestion here. Releasing a rudimentary update that gives this functionality. 🎉
