### ISSUE TITLE
0x0 SVGs detected on deviantart.com

### ISSUE THREAD

**Issue by chrismessina** [rossmoody/svg-gobbler#70]
**Describe the bug**
SVG elements that have 0 width and height in HTML are grabbed but exported from SVG Grabber at 1x1:

```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="0" height="0" viewBox="0 0 100 167" preserveAspectRatio="xMidYMid meet">
<path d=" M100 0 L99.96 0 L99.95 0 L71.32 0 L68.26 3.04 L53.67 30.89 L49.41 33.35 L0 33.35 L0 74.97 L26.40 74.97 L29.15 77.72 L0 133.36 L0 166.5 L0 166.61 L0 166.61 L28.70 166.6 L31.77 163.55 L46.39 135.69 L50.56 133.28 L100 133.28 L100 91.68 L73.52 91.68 L70.84 89 L100 33.33 "></path>
</svg>
```

**To Reproduce**
1. Go to deviantart.com
2. Click on SVG Grabber
3. Notice that SVG assets are reported as having 0x0 dimensions
4. Attempt to copy unoptimized an SVG asset and paste it into Sketch
5. Notice that the pasted asset is 1x1 (which also means that original aspect ratio is off)

**Expected behavior**
When HTML defines the size of an asset as having 0 width and height, SVG Grabber should ignore those values.

**Screenshots**
![CleanShot 2021-01-10 at 13 21 12@2x](https://user-images.githubusercontent.com/22610/104135796-082ecb80-5347-11eb-8d17-f7077dabf0e5.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.1 (20C69)
 - Browser: Chrome
 - Version: Version 87.0.4280.88 (Official Build) (x86_64)

**Comment by rossmoody** [comment]
This is super interesting. When I paste optimized and unoptimized of any of those into Figma, they render at their viewBox size. When I paste the same code into Sketch it's all jacked up at 1x1 as you say. 

I'm unsure how to fix this one. Could use suggestions if ya have any. I think since the original icon is being grabbed this is more a fault of Sketch than something I can solve. 

For instance, the menu icon in the DOM is this:
```
<svg width="0" height="0" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g><path d="M6 4h12v3H6zM6 18h12v3H6zM2 11h20v3H2z"></path></g></svg>
```

## Optimized with SVG Gobbler
```
<svg width="0" height="0" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M6 4h12v3H6zm0 14h12v3H6zm-4-7h20v3H2z"/></svg>
```

## Unoptimized
```
<svg width="0" height="0" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g><path d="M6 4h12v3H6zM6 18h12v3H6zM2 11h20v3H2z"/></g></svg>
```

**Comment by chrismessina** [comment]
This is not ideal, but what I end up doing is downloading the SVG, opening it in Gapplin, and then exporting as a PDF, and opening the PDF in Sketch! It's a pain, but when I'm motivated, it works reliably. So I dunno if that it makes sense to offer PDF as a copyable/downloadable alternative format?

**Comment by rossmoody** [comment]
I'm still tinkering with this. Sketch gets upset about the width and height declarations being 0. If those are removed it brings the SVG in ok (still not at the ideal viewBox dimensions). 

Seems a shame SVGO doesn't strip out those properties.

**Comment by rossmoody** [comment]
Gonna close this one since the SVGs are being exported as they are in the DOM. I think this is more on the Sketch side.
