### ISSUE TITLE
Fails to detect some SVGs

### ISSUE THREAD

**Issue by zhudock** [rossmoody/svg-gobbler#99]
**Describe the bug**
Fails to detect some SVGs

**To Reproduce**

1. Go to [OriginalTrilogy](https://originaltrilogy.com/)
2. The logo in their header bar is an SVG
3. Click the SVG Gobbler Icon
4. See error "No available SVGs to gobble"

**Expected behavior**
The logo should be able to be extracted from the header

**Desktop (please complete the following information):**

- OS: Win 10
- Browser : Firefox
- Version : 90.0.2

**Comment by rossmoody** [comment]
Thank you thank you thank you for prompting this bug with this site to help troubleshoot. I'm midway through working through it but your prompt massively improved/simplified the logic for building svgs from sprite symbol sheet fetch calls! 
![image](https://user-images.githubusercontent.com/29072694/128610291-a56e9a95-b3fe-4330-89fc-788aef70f090.png)
